name: CI

permissions:
  contents: read

on:
  pull_request:
    branches: ['main']
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  pipeline-steps:
    name: ${{ matrix.job-name }}
    runs-on: ubuntu-latest
    timeout-minutes: ${{ matrix.timeout-minutes }}
    strategy:
      matrix:
        include:
          - job-name: Install dependencies
            command: ''
            timeout-minutes: 5
          - job-name: Lint
            command: npm run lint
            timeout-minutes: 5
          - job-name: Unit tests
            command: npm test -- --watch=false --browsers=ChromeHeadless
            timeout-minutes: 5
          - job-name: Build
            command: npm run build:prod
            timeout-minutes: 5
      max-parallel: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run command
        if: matrix.command != ''
        run: ${{ matrix.command }}
