name: CI

permissions:
  contents: read

on:
  pull_request:
    branches: ['main']
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Restore npm cache
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install packages
        run: npm ci

  quality:
    name: ${{ matrix.label }}
    runs-on: ubuntu-latest
    needs: install
    strategy:
      fail-fast: false
      matrix:
        include:
          - label: Lint
            command: |
              npm run lint
          - label: Test scripts
            command: |
              npm run test:scripts
          - label: Test angular
            command: |
              npm run test:angular -- --watch=false --browsers=ChromeHeadlessNoSandbox
          - label: Build
            command: |
              npm run build:prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Restore npm cache
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install packages
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run ${{ matrix.label }}
        run: ${{ matrix.command }}

  check:
    name: Check all ok
    runs-on: ubuntu-latest
    needs: quality
    if: ${{ always() }}
    steps:
      - name: Verify status
        run: |
          if [ "${{ needs.quality.result }}" != "success" ]; then
            echo "Quality checks did not succeed"
            exit 1
          fi
          echo "All checks passed"
